# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
      - image: circleci/mysql:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install software-properties-common package
          command: 'sudo apt-get install software-properties-common python-software-properties'

      - run:
          name: Add java PPA
          command: 'sudo add-apt-repository ppa:openjdk-r/ppa'

      - run:
          name: Update package manager
          command: 'sudo apt-get update '
      
      - run:
          name: Install java
          command: 'sudo apt-get install openjdk-8-jdk'

      - run:
          name: Show java version
          command: 'java -version'

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm test


